# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aoc-2023',
                'doc_host': 'https://astaff.github.io',
                'git_url': 'https://github.com/astaff/aoc-2023',
                'lib_path': 'aoc_2023'},
  'syms': {'aoc_2023.core': {'aoc_2023.core.read_input': ('core.html#read_input', 'aoc_2023/core.py')}}}
