# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_input']

# %% ../nbs/00_core.ipynb 3
def read_input(filename: str) -> str:
    with open(filename) as f:
        _input = f.read()
    return _input
